---
Description: Downloads the latest version of Docker and creates a package.
Identifier: com.github.smithjw.pkg.Docker
ParentRecipe: com.github.smithjw.download.Docker
MinimumVersion: '2.3'

Input:
  NAME: Docker

Process:
  - Processor: PkgRootCreator
    Arguments:
      pkgdirs:
        Applications: '0775'
      pkgroot: '%RECIPE_CACHE_DIR%/payload'

  - Processor: Copier
    Arguments:
      source_path: '%pathname%/Docker.app'
      destination_path: '%pkgroot%/Applications/Docker.app'

  - Processor: PkgCreator
    Arguments:
      pkg_request:
        chown:
          - group: admin
            path: Applications
            user: root
        id: '%bundleid%'
        options: purge_ds_store
        pkgdir: '%RECIPE_CACHE_DIR%'
        pkgname: '%NAME%-%ARCHITECTURE%-%version%'
        scripts: scripts

  - Processor: com.github.smithjw.processors/FriendlyPathDeleter
    Arguments:
      fail_deleter_silently: true
      path_list:
        - '%RECIPE_CACHE_DIR%/payload'
