---
Description: Downloads the latest version of Docker and creates a package.
Identifier: com.github.smithjw.pkg.Docker
ParentRecipe: com.github.smithjw.download.Docker
MinimumVersion: '2.3'

Input:
  NAME: Docker
  ARCHITECTURE: x86_64

Process:
  - Processor: PkgRootCreator
    Arguments:
      pkgroot: '%RECIPE_CACHE_DIR%/payload'
      pkgdirs:
        pkgroot: '0775'
        scripts: '0775'

  - Processor: PlistReader
    Arguments:
      info_path: '%RECIPE_CACHE_DIR%/downloads/Docker-%ARCHITECTURE%.dmg/Docker.app/Contents/Info.plist'
      plist_keys:
        CFBundleShortVersionString: version
        CFBundleIdentifier: bundleid
        CFBundleName: app_name

  - Processor: Copier
    Arguments:
      source_path: '%RECIPE_CACHE_DIR%/downloads/Docker-%ARCHITECTURE%.dmg'
      destination_path: '%RECIPE_CACHE_DIR%/payload/scripts/Docker-%ARCHITECTURE%-%version%.dmg'

  - Processor: FileCreator
    Arguments:
      file_path: '%RECIPE_CACHE_DIR%/payload/scripts/postinstall'
      file_mode: '0755'
      file_content: |
        #!/bin/bash
        # https://forums.docker.com/t/feature-request-cli-tool-for-automated-installation/18334/4
        # https://github.com/autopkg/chilcote-recipes/blob/master/Docker/Docker.munki.recipe
        # https://github.com/docker/for-mac/issues/2359
        # https://macadmins.slack.com/archives/C056155B4/p1716206699338559

        logged_in_user=$( scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && ! /loginwindow/ { print $3 }' )
        declare -r docker_bundle_dir=/Applications/Docker.app/Contents
        declare -r privtools=/Library/PrivilegedHelperTools
        declare -r usr_local_bin=/usr/local/bin

        /usr/bin/hdiutil attach "Docker-%ARCHITECTURE%-%version%.dmg" -mountpoint "/Volumes/Docker-%version%" -nobrowse

        if [[ -e /Library/LaunchDaemons/com.docker.vmnetd.plist ]] ; then
          /bin/launchctl unload /Library/LaunchDaemons/com.docker.vmnetd.plist
        fi

        "/Volumes/Docker-%version%/Docker.app/Contents/MacOS/install" --accept-license --user "${logged_in_user}"

        [[ ! -d ${usr_local_bin} ]] && /bin/mkdir -p ${usr_local_bin} ; /bin/chmod 1755 ${usr_local_bin}
        [[ ! -d ${privtools} ]] && /bin/mkdir -p ${privtools} ; /bin/chmod 1755 ${privtools}

        for tool in docker docker-compose docker-diagnose docker-machine notary; do
          /bin/ln -sf ${docker_bundle_dir}/Resources/bin/${tool} /usr/local/bin
        done

        /usr/bin/hdiutil detach "/Volumes/Docker-%version%"

        exit 0

  - Processor: PkgCreator
    Arguments:
      pkg_request:
        id: '%bundleid%'
        options: purge_ds_store
        pkgdir: '%RECIPE_CACHE_DIR%'
        pkgname: '%NAME%-%ARCHITECTURE%-%version%'
        pkgroot: '%RECIPE_CACHE_DIR%/payload/pkgroot'
        scripts: '%RECIPE_CACHE_DIR%/payload/scripts'
        version: '%version%'

  - Processor: com.github.smithjw.processors/FriendlyPathDeleter
    Arguments:
      fail_deleter_silently: true
      path_list:
        - '%RECIPE_CACHE_DIR%/payload'
