---
Comment: |
  Use the ARCHITECTURE and DOWNLOAD_TYPE keys to determine whether the Intel (amd64) or Apple Silicon (arm64) version
  of Docker for Mac is downloaded. Defaults to Intel if not overridden.
  Intel: "--key ARCHITECTURE=x86_64 --key DOWNLOAD_TYPE=amd64"
  Apple Silicon: "--key ARCHITECTURE=arm64 --key DOWNLOAD_TYPE=arm64"
Description: Downloads the latest version of Docker, packages it, then installs.
Identifier: com.github.smithjw.install.Docker
ParentRecipe: com.github.smithjw.pkg.Docker
MinimumVersion: '2.3'

Input:
  NAME: Docker
  ARCHITECTURE: x86_64

Process:
  - Processor: Installer
