---
Comment: |
  Utilises Shared Processors from https://github.com/jgstew/jgstew-recipes
  Use the ARCHITECTURE and DOWNLOAD_TYPE keys to determine whether the Intel (amd64) or Apple Silicon (arm64) version
  of Docker for Mac is downloaded. Defaults to Intel if not overridden.
  Intel: "--key ARCHITECTURE=x86_64 --key DOWNLOAD_TYPE=amd64"
  Apple Silicon: "--key ARCHITECTURE=arm64 --key DOWNLOAD_TYPE=arm64"
Description: Downloads the latest version of Docker.
Identifier: com.github.smithjw.download.Docker
MinimumVersion: '2.3'

Input:
  NAME: Docker
  ARCHITECTURE: x86_64
  DOWNLOAD_TYPE: amd64

Process:
  - Processor: URLTextSearcher
    Arguments:
      re_pattern: ((\w+):\/\/(\S*)(%DOWNLOAD_TYPE%)(\S*)(dmg)(?=\?))
      result_output_var_name: match
      url: https://www.docker.com/get-started

  - Processor: com.github.jgstew.SharedProcessors/URLDownloaderPython
    Arguments:
      filename: 'Docker-%ARCHITECTURE%.dmg'
      download_dir: '%RECIPE_CACHE_DIR%/downloads'
      url: '%match%'

  - Processor: EndOfCheckPhase
  - Processor: com.github.jgstew.SharedProcessors/StopProcessingIfDownloadUnchanged

  - Processor: CodeSignatureVerifier
    Arguments:
      input_path: '%RECIPE_CACHE_DIR%/downloads/Docker-%ARCHITECTURE%.dmg/Docker.app'
      deep_verification: true
      strict_verification: true
      requirement: >-
        anchor apple generic and identifier "com.docker.docker" and
        (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or
        certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and
        certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and
        certificate leaf[subject.OU] = "9BNSXJN65R")
